# Generated by Django 4.2.16 on 2024-11-04 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transcription", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_caseBrief", models.TextField(blank=True, null=True)),
                ("formatted_Casebrief", models.TextField(blank=True, null=True)),
                (
                    "pdf_file_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transcription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transcription.transcription",
                    ),
                ),
            ],
        ),
    ]
