# Generated by Django 4.2.16 on 2024-11-04 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transcription", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiarizedSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diarization_data", models.TextField(blank=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "transcription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transcription.transcription",
                    ),
                ),
            ],
        ),
    ]
