# Generated by Django 4.2.16 on 2024-11-04 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transcription", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_file", models.FileField(upload_to="audio_chunks/")),
                ("chunk_index", models.IntegerField()),
                ("transcription_text", models.TextField(blank=True, null=True)),
                ("diarization_data", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transcription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transcription.transcription",
                    ),
                ),
            ],
        ),
    ]
