name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to Heroku (Force Push)
        run: |
          git remote add heroku https://git.heroku.com/themis-ai.git
          git config --global credential.helper store
          echo "https://$HEROKU_API_KEY:@git.heroku.com" > ~/.git-credentials
          git push --force heroku HEAD:main
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HF_AUTH_TOKEN: ${{ secrets.HF_AUTH_TOKEN }}
          AAI_KEY: ${{ secrets.AAI_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Capture Heroku Logs on Failure
        if: failure()
        run: |
          heroku logs --app themis-ai --source app --dyno web.1
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
