name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to Heroku (Force Push)
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "themis-ai"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          dontuseforce: 0  # Allow force pushing
        env:
          HF_AUTH_TOKEN: ${{ secrets.HF_AUTH_TOKEN }}
          AAI_KEY: ${{ secrets.AAI_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Capture Heroku Logs on Failure
        if: failure()
        run: |
          heroku logs --app themis-ai --source app --dyno web.1
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
