  name: Django CI

  on: [push, pull_request]

  jobs:
    black:
      name: Check code formatting with Black
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Install Black
          run: |
            pip install black
        - name: Lint files
          run: |
            black --check .

    migrations:
      name: Run migrations
      runs-on: ubuntu-latest
      env:
        HF_AUTH_TOKEN: ${{ secrets.HF_AUTH_TOKEN }}
        AAI_KEY: ${{ secrets.AAI_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up Python environment
          uses: actions/setup-python@v2
          with:
            python-version: 3.11
        - name: Install dependencies
          run: |
            pip install -r requirements.txt
        - name: Run migrations
          run: |
            python manage.py migrate

    tests:
      name: Run tests
      runs-on: ubuntu-latest
      env:
        HF_AUTH_TOKEN: ${{ secrets.HF_AUTH_TOKEN }}
        AAI_KEY: ${{ secrets.AAI_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up Python environment
          uses: actions/setup-python@v2
          with:
            python-version: 3.11
        - name: Install dependencies
          run: |
            pip install -r requirements.txt
        - name: Run tests
          run: |
            python manage.py test


